### ISSUE TITLE
Как сделать livereload без перезагрузки браузера?

### ISSUE THREAD

**Issue by nikolays93** [andreyalexeich/gulppack-scss#12]
Помниться в предыдущей версии браузера у меня работал лайфрелоад средствами иньекции стилей в браузер, а не перезапускал страницу. В вашем скрипте такое возможно?

**Comment by andreyalexeich** [comment]
Нет, наверное невозможно :)

**Comment by nikolays93** [comment]
Жаль, я пытался настроить. Но что то не совсем вкурил в gulp4 series и parallels.
